// SIGNUP STATUS
export const STATUS_CODE_CREATED = 201;
export const STATUS_CODE_INVALID_SIGNUP = 400;

// LOGIN STATUS
export const STATUS_CODE_LOGIN = 200;
export const STATUS_CODE_MISSING_FIELD = 400;
export const STATUS_CODE_INCORRECT_PASSWORD = 401;
export const STATUS_CODE_INVALID_USER = 404;
export const STATUS_DATABASE_FAILURE = 500;

export const STATUS_CODE_CONFLICT = 409;
