name: Production Build

on:
  push:
    branches: [ release ]

jobs:
  deploy-frontend:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: Staging Build
      run: |
        npm run build
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: "peerprepfe"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "ap-southeast-1"
        SOURCE_DIR: "frontend/build"

  deploy-user-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate user-service deployment package
      working-directory: user-service
      run: zip -r user-service.zip . 
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
    - name: Deploy user-service
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        application_name: "user-service"
        environment_name: "user-service-env"
        region: "ap-southeast-1"
        version_label: "user-service-${{ steps.format-time.outputs.replaced }}"
        deployment_package: user-service/user-service.zip

  deploy-matching-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate matching-service deployment package
      working-directory: matching-service
      run: zip -r "matching-service.zip" * .ebextensions
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
    - name: Deploy matching-service
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        application_name: "matching-service"
        environment_name: "matching-service-env"
        region: "ap-southeast-1"
        version_label: "matching-service-${{ steps.format-time.outputs.replaced }}"
        deployment_package: matching-service/matching-service.zip

  deploy-question-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate question-service deployment package
      working-directory: question-service
      run: zip -r "question-service.zip" * node_modules
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
    - name: Deploy question-service
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        application_name: "question-service"
        environment_name: "question-service-env"
        region: "ap-southeast-1"
        version_label: "question-service-${{ steps.format-time.outputs.replaced }}"
        deployment_package: question-service/question-service.zip

  deploy-collab-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate collab-service deployment package
      working-directory: collab-service
      run: zip -r collab-service.zip * .ebextensions
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
    - name: Deploy collab-service
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        application_name: "collab-service"
        environment_name: "collab-service-env"
        region: "ap-southeast-1"
        version_label: "collab-service-${{ steps.format-time.outputs.replaced }}"
        deployment_package: collab-service/collab-service.zip

  deploy-chat-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate chat-service deployment package
      working-directory: chat-service
      run: zip -r chat-service.zip * .ebextensions 
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
    - name: Deploy chat-service
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        application_name: "chat-service"
        environment_name: "chat-service-env"
        region: "ap-southeast-1"
        version_label: "chat-service-${{ steps.format-time.outputs.replaced }}"
        deployment_package: chat-service/chat-service.zip
